# AR1
ARMODEL_ALPHA = 0.5
ARMODEL_GAMMA = 0.1
ARMODEL_DELTA = 0.05

# Common
ARMODEL_SIGMA = 0.1
ARMODEL_TRAINING_RATIO = 0.8

# Ridge
ARMODEL_RIDGE_ALPHA = 0.1
ARMODEL_RIDGE_LEARNING_RATE = 0.01
ARMODEL_RIDGE_EPOCHS = 1000