from config.paths import *
from config.common import *
from config.ttm import *
from config.ttm_dnpus import *
from config.timesfm import *
from config.tcn import *
from config.transformer import *
from config.only_decoder import *
from config.static import *
from config.data import *
from config.narma import *
from config.armodel import *