from config.paths import *
from config.common import *
from config.ttm import *
from config.timesfm import *
from config.tcn import *
from config.static import *
from config.informer import *
from config.lightts import *
from config.data import *
from config.narma import *
from config.armodel import *